#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''

'''

RESULT_PATH = '../result/'

"import lib"
import math
import matplotlib.pyplot as plt
from matplotlib.pyplot import MultipleLocator

"Plot the line"
def plot_line(x, y, x_label, y_label, x_locator, y_locator, title):

    #
    plt.plot(x, y, c='deepskyblue')
    plt.xticks(rotation=45)
    "Make the plot title"
    plt.title(title)
    plt.tick_params(axis='both', which='major', labelsize=14)
    plt.xlabel(x_label, fontsize=12)
    plt.ylabel(y_label, fontsize=12)
    "Set x axis locator"
    x_major_locator = MultipleLocator(x_locator)
    "Set y axis locator"
    y_major_locator = MultipleLocator(y_locator)
    ax = plt.gca()
    ax.xaxis.set_major_locator(x_major_locator)
    ax.yaxis.set_major_locator(y_major_locator)
    "Set x axis range"
    plt.xlim(1, len(x))
    "Set y axis range"
    plt.ylim(0, math.ceil(max(y)))
    "Save the plot"
    plt.savefig(RESULT_PATH+title+".png")
    "Show the plot"
    plt.show()
